// Mock data for the dashboard UI until the database is wired up.

export const currentUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  isPro: false,
};

export const itemTypes = [
  { id: "snippet", name: "Snippets", icon: "Code", color: "#3b82f6", isPro: false },
  { id: "prompt", name: "Prompts", icon: "Sparkles", color: "#8b5cf6", isPro: false },
  { id: "command", name: "Commands", icon: "Terminal", color: "#f97316", isPro: false },
  { id: "note", name: "Notes", icon: "StickyNote", color: "#fde047", isPro: false },
  { id: "file", name: "Files", icon: "File", color: "#6b7280", isPro: true },
  { id: "image", name: "Images", icon: "Image", color: "#ec4899", isPro: true },
  { id: "link", name: "Links", icon: "Link", color: "#10b981", isPro: false },
];

export const collections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    typeIds: ["snippet", "note", "link"],
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    typeIds: ["snippet"],
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    typeIds: ["file", "note"],
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    typeIds: ["snippet", "prompt", "note"],
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    typeIds: ["command"],
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    typeIds: ["prompt", "note"],
  },
];

export const items = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    content: "export function useAuth() { /* ... */ }",
    typeId: "snippet",
    language: "typescript",
    tags: ["react", "auth", "hooks"],
    isFavorite: true,
    isPinned: true,
    collectionIds: ["col_1"],
    createdAt: "2026-04-10",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    content: "export async function fetchWithRetry() { /* ... */ }",
    typeId: "snippet",
    language: "typescript",
    tags: ["api", "error-handling"],
    isFavorite: false,
    isPinned: true,
    collectionIds: ["col_1"],
    createdAt: "2026-04-10",
  },
  {
    id: "item_3",
    title: "Code Review Prompt",
    description: "System prompt for AI-assisted code reviews",
    content: "You are a senior engineer reviewing a pull request...",
    typeId: "prompt",
    tags: ["review"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col_6"],
    createdAt: "2026-04-08",
  },
  {
    id: "item_4",
    title: "Undo last commit (keep changes)",
    content: "git reset --soft HEAD~1",
    typeId: "command",
    tags: ["git"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col_5"],
    createdAt: "2026-04-05",
  },
  {
    id: "item_5",
    title: "Next.js App Router Docs",
    url: "https://nextjs.org/docs/app",
    typeId: "link",
    tags: ["nextjs", "docs"],
    isFavorite: true,
    isPinned: false,
    collectionIds: ["col_1"],
    createdAt: "2026-04-02",
  },
];
